---
- hosts: zabbix
  tasks:
    - name: Install zabbix repo
      yum:
        name: rpm -Uvh https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm
        state: present
    
    - name: Add Repo Remi PHP 7
      yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present
    
    - name: Activate Remi PHP74
      yum_repository:
        name: remi-php74
        enabled: yes

    - name: Install zabbix server mysql
        yum:
          name: zabbix-server-mysql
          state: present
  
      - name: Install zabbix frontend apache
        yum:
          name: zabbix-web-mysql
          state: present          
    
    - name: Configure zabbix php web frontend
      template:
        src: zabbix.conf.j2
        dest: /etc/httpd/conf.d/zabbix.conf