# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

## Lab Zabbix Ansible
# ansible-control : 192.168.57.11
# database : 192.168.57.21
# zabbix : 192.168.57.22


Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.memory = 512
    vb.customize ["modifyvm", :id, "--groups", "/Zabbix-Lab"]
  end

  ## database.hl.local
  config.vm.define "database.hl.local" do |machine|
    machine.vm.hostname = "database.hl.local"
    machine.vm.box = "centos/7"
    machine.vm.network "private_network", ip: "192.168.57.21"
    machine.vm.network "forwarded_port", guest: 3306, host: 3306
  end
  
  ## zabbix.hl.local
  config.vm.define "zabbix.hl.local" do |machine|
    machine.vm.hostname = "zabbix.hl.local"
    machine.vm.box = "centos/7"
    machine.vm.network "private_network", ip: "192.168.57.22"
  end
end

