---
  # tasks file for database
  - name: Install mariadb
    yum:
      name: ['mariadb', 'MySQL-python']
      state: present
  
  - name: Enable and start mariadb and firewalld
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - mariadb
      - firewalld
  
  - name: Configure firewall for mysql
    firewalld:
      service: mysql
      permanent: yes
      state: enabled
      immediate: yes
  
  
  - name: Create database zabbix
    mysql_db:
      name: "{{ DBNAME }}"
      state: present
      encoding: utf8
      login_password: "{{ DBROOTPASSWD }}"
      config_file: /etc/my.cnf
 


  - name: Remove user "{{ DBUSERNAME }}"
    mysql_user:
      name: "{{ DBUSERNAME }}"
      login_password: "{{ DBROOTPASSWD }}"
      state: absent
      config_file: /etc/my.cnf

  - name: Create database user with password
    mysql_user:
      name: "{{ DBUSERNAME }}"
      password: "{{ DBPASSWD }}"
      priv: '{{ DBNAME }}.*:ALL,GRANT'
      state: present
      host: "{{ HOSTZABBIXSERVER }}"
      login_password: "{{ DBROOTPASSWD }}"
      config_file: /etc/my.cnf
    tags:
      - createdbuser
  
  
