---
# tasks file for database
- name: Install mariadb
  yum:
    name: mariadb
    state: present

- name: Enable and start mariadb and firewalld
  service:
    name: ['mariadb', 'firewalld']
    state: started
    enabled: yes



- name: Create database zabbix
  mysql_db:
    name: zabbix
    state: present

- name: Create database user with password
  mysql_user:
    name: zabbix
    password: "{{ DBPASSWD }}"
    priv: 'zabbix.*:ALL,GRANT'
    state: present

- name: Configure firewall for mysql
  firewalld:
    service: mysql
    permanent: yes
    state: enabled
    immediate: yes
